Separate README from catbuffer's
nemtech/catbuffer-generators pull request #129
Opened 2020-10-23 10:54 UTC by segfaultxavi

Now they are independent.

Related to nemtech/catbuffer#55.

2020-11-02 18:37 UTC, fboucquez requested changes

2020-11-02 18:37 UTC, fboucquez commented on README.md
> +1. Clone the ``catbuffer-generators`` repository:
Use command

`git clone --recurse-submodules https://github.com/nemtech/catbuffer-generators`

To include catbuffer when cloning

2020-11-02 18:37 UTC, fboucquez commented on README.md
> +3. Clone the ``catbuffer`` repository inside the ``catbuffer-generators`` folder:
Not required when using --recurse-submodules

2020-11-02 18:37 UTC, fboucquez commented on README.md
> +Or use any of the language-specific scripts like ``generate_typescript.sh``.
Should we clarify that each language script also compiles and creates the artifacts? The language-specific scripts generate the artifacts in the /build folder

2020-11-03 10:46 UTC, segfaultxavi commented on README.md
> +1. Clone the ``catbuffer-generators`` repository:
Done

2020-11-03 10:46 UTC, segfaultxavi commented on README.md
> +3. Clone the ``catbuffer`` repository inside the ``catbuffer-generators`` folder:
Done

2020-11-03 10:46 UTC, segfaultxavi commented on README.md
> +Or use any of the language-specific scripts like ``generate_typescript.sh``.
Done

2020-11-24 08:45 UTC, segfaultxavi commented
@fboucquez Any reason why this can't be landed?

2020-11-24 17:03 UTC, fboucquez approved these changes

2020-11-24 17:03 UTC, merged